use_frameworks!

target 'PoporIDBankCard_Example' do
    # 忽略pod第三方库文件警告
    inhibit_all_warnings!
    
    pod 'PoporIDBankCard', :path => '../'
    
    target 'PoporIDBankCard_Tests' do
        inherit! :search_paths
        
        
    end
end
